### ISSUE TITLE
How about Windows?

### ISSUE THREAD

**Issue by pdigre** [theia-ide/theia-xtext#5]
Requirements:

- Java - cannot be newer than 8
- NodeJS - cannot be newer than version 9
- Gradle
- Python
- Yarn

Then I get this error from yarn
"error C:\git\theia-xtext\node_modules\nsfw: Command failed."

This is described in a Theia issue - Which basically requires the Ubuntu "build-essential"
https://github.com/theia-ide/theia/issues/2174

How do I go about getting this to work on my Windows PC ?

**Comment by monaka** [comment]
This issue is not about Theia but NodeJS on Windows.
You'll find the way to install build tools by googling `npm install --global --production windows-build-tools`

**Comment by pdigre** [comment]
A little late answer, but it is correct ! Please update the instructions.
