### ISSUE TITLE
Build Fails

### ISSUE THREAD

**Issue by amirsaad2015** [theia-ide/theia-xtext#6]
I receive the following error when trying to run the command "yarn install" to build this Theia application: 

Node Version: 8.10.0
OS: macOS High Sierra version 10.13.5

MT-110778:theia-xtext asaad$ yarn install
yarn install v1.7.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning Pattern ["rimraf@latest"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-rimraf-2.6.2-2ed8150d24a16ea8651e6d6ef0f47c4158ce7a36" as pattern ["rimraf@^2.6.1","rimraf@^2.2.8","rimraf@^2.2.8","rimraf@^2.5.4","rimraf@2","rimraf@^2.6.1","rimraf@^2.6.2","rimraf@2","rimraf@^2.5.4","rimraf@^2.5.4","rimraf@^2.6.1","rimraf@^2.5.1"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/editor@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/editor-0.4.0-next.d11a5b63-dc05a824886d230f003b180142ca0d904dab19ab" as pattern ["@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63","@theia/editor@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/filesystem@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/filesystem-0.4.0-next.d11a5b63-89dfc682f5c9db8db52388a638a02676e9338cec" as pattern ["@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63","@theia/filesystem@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/markers@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/markers-0.4.0-next.d11a5b63-134b1fb6f79fe604fd96901f9e8847c9887d077a" as pattern ["@theia/markers@0.4.0-next.d11a5b63","@theia/markers@0.4.0-next.d11a5b63","@theia/markers@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/monaco@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/monaco-0.4.0-next.d11a5b63-2b1dc600c0f792123c11d2bf989889006fcdce04" as pattern ["@theia/monaco@0.4.0-next.d11a5b63","@theia/monaco@0.4.0-next.d11a5b63","@theia/monaco@0.4.0-next.d11a5b63","@theia/monaco@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/navigator@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/navigator-0.4.0-next.d11a5b63-3280ab0fbbb795217d680c902b5477936769d065" as pattern ["@theia/navigator@0.4.0-next.d11a5b63","@theia/navigator@0.4.0-next.d11a5b63","@theia/navigator@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/outline-view@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/outline-view-0.4.0-next.d11a5b63-56d1c8990b5b8a15752776c6d5a290b896272711" as pattern ["@theia/outline-view@0.4.0-next.d11a5b63","@theia/outline-view@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/output@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/output-0.4.0-next.d11a5b63-b4a8e1a6c921debe907e7cb3f2442cc2537e99a6" as pattern ["@theia/output@0.4.0-next.d11a5b63","@theia/output@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/preferences@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/preferences-0.4.0-next.d11a5b63-6a89f37b72f51d89dcf85578b1185a6c92f00b5b" as pattern ["@theia/preferences@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/process@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/process-0.4.0-next.d11a5b63-6f657eabb0136399e62bd6701b2151c2ce3a7c7d" as pattern ["@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63","@theia/process@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/terminal@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/terminal-0.4.0-next.d11a5b63-57db0260383bb4585aa408353ced636e10f4f89e" as pattern ["@theia/terminal@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/userstorage@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/userstorage-0.4.0-next.d11a5b63-a9d8b3d8d597d0fb044ae0c7e3ea53f1c0263851" as pattern ["@theia/userstorage@0.4.0-next.d11a5b63","@theia/userstorage@0.4.0-next.d11a5b63","@theia/userstorage@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning Pattern ["@theia/workspace@next"] is trying to unpack in the same destination "/Users/asaad/Library/Caches/Yarn/v1/npm-@theia/workspace-0.4.0-next.d11a5b63-4bf1d242b8d88d0a540dc446fcfd5c301daf7da8" as pattern ["@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63","@theia/workspace@0.4.0-next.d11a5b63"]. This could result in non-deterministic behavior, skipping.
warning vscode-base-languageclient@0.0.1-alpha.3: The engine "vscode" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning "workspace-aggregator-9607be9a-448a-4865-b288-cf7241a5902e > browser-app > @theia/cli > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
[4/4] 📃  Building fresh packages...
$ lerna run prepare
lerna info version 2.4.0
@theia/xtext-dsl-extension: > @theia/xtext-dsl-extension@0.1.0 prepare /Users/asaad/Desktop/theia-xtext/xtext-dsl-extension
@theia/xtext-dsl-extension: > yarn run clean && yarn run build
@theia/xtext-dsl-extension: yarn run v1.7.0
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rimraf lib
@theia/xtext-dsl-extension: Done in 0.14s.
@theia/xtext-dsl-extension: yarn run v1.7.0
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ tsc && yarn run copy-ls
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(12,46): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(12,75): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(12,99): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,54): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,78): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,81): error TS1109: Expression expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,97): error TS1109: Expression expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,122): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,130): error TS1128: Declaration or statement expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(14,138): error TS1005: ',' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(27,48): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(27,49): error TS1109: Expression expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(27,50): error TS1109: Expression expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(27,68): error TS1005: '(' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(27,69): error TS1005: ')' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(29,30): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(29,54): error TS1005: ';' expected.
@theia/xtext-dsl-extension: ../../../node_modules/@types/prop-types/index.d.ts(29,57): error TS1109: Expression expected.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 2.
@theia/xtext-dsl-extension: npm ERR! code ELIFECYCLE
@theia/xtext-dsl-extension: npm ERR! errno 1
@theia/xtext-dsl-extension: npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run build`
@theia/xtext-dsl-extension: npm ERR! Exit status 1
@theia/xtext-dsl-extension: npm ERR! 
@theia/xtext-dsl-extension: npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
@theia/xtext-dsl-extension: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@theia/xtext-dsl-extension: npm ERR! A complete log of this run can be found in:
@theia/xtext-dsl-extension: npm ERR!     /Users/asaad/.npm/_logs/2018-08-17T00_16_12_066Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run build`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
lerna ERR! 
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     /Users/asaad/.npm/_logs/2018-08-17T00_16_12_066Z-debug.log
lerna ERR! 
lerna ERR! 
lerna ERR! > @theia/xtext-dsl-extension@0.1.0 prepare /Users/asaad/Desktop/theia-xtext/xtext-dsl-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR! 
lerna ERR! yarn run v1.7.0
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.14s.
lerna ERR! yarn run v1.7.0
lerna ERR! $ tsc && yarn run copy-ls
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(12,46): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(12,75): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(12,99): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,54): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,78): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,81): error TS1109: Expression expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,97): error TS1109: Expression expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,122): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,130): error TS1128: Declaration or statement expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(14,138): error TS1005: ',' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(27,48): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(27,49): error TS1109: Expression expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(27,50): error TS1109: Expression expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(27,68): error TS1005: '(' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(27,69): error TS1005: ')' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(29,30): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(29,54): error TS1005: ';' expected.
lerna ERR! ../../../node_modules/@types/prop-types/index.d.ts(29,57): error TS1109: Expression expected.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/asaad/Desktop/theia-xtext/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
(node:65659) UnhandledPromiseRejectionWarning: Error: Command failed: npm run prepare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asaad/.npm/_logs/2018-08-17T00_16_12_066Z-debug.log

> @theia/xtext-dsl-extension@0.1.0 prepare /Users/asaad/Desktop/theia-xtext/xtext-dsl-extension
> yarn run clean && yarn run build

yarn run v1.7.0
$ rimraf lib
Done in 0.14s.
yarn run v1.7.0
$ tsc && yarn run copy-ls
../../../node_modules/@types/prop-types/index.d.ts(12,46): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(12,75): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(12,99): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(14,54): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(14,78): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(14,81): error TS1109: Expression expected.
../../../node_modules/@types/prop-types/index.d.ts(14,97): error TS1109: Expression expected.
../../../node_modules/@types/prop-types/index.d.ts(14,122): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(14,130): error TS1128: Declaration or statement expected.
../../../node_modules/@types/prop-types/index.d.ts(14,138): error TS1005: ',' expected.
../../../node_modules/@types/prop-types/index.d.ts(27,48): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(27,49): error TS1109: Expression expected.
../../../node_modules/@types/prop-types/index.d.ts(27,50): error TS1109: Expression expected.
../../../node_modules/@types/prop-types/index.d.ts(27,68): error TS1005: '(' expected.
../../../node_modules/@types/prop-types/index.d.ts(27,69): error TS1005: ')' expected.
../../../node_modules/@types/prop-types/index.d.ts(29,30): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(29,54): error TS1005: ';' expected.
../../../node_modules/@types/prop-types/index.d.ts(29,57): error TS1109: Expression expected.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

    at Promise.all.then.arr (/Users/asaad/Desktop/theia-xtext/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:65659) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:65659) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by svenefftinge** [comment]
This was due to an intermediate or broken release of Theia@next.

**Comment by SharkJ** [comment]
Hi, is there a way to overcome this?
